### ISSUE TITLE
Start the mirror on startup

### ISSUE THREAD

**Issue by kurtdb** [evancohen/smart-mirror#109]
We get more and more questions from people who want to run the mirror on startup. There have been a few people that have already done this, so it might be a good idea to document this in the readme.

Maybe someone can pick this up?

**Comment by Shubham0209** [comment]
@kurtdb i had saved the following comments from chat..

If anyone wants the mirror to autostart you can create the following script in the root of your users home :
/home/pi/smart-start.sh

!/bin/bash

export DISPLAY=:0

export XAUTHORITY=/home/pi/.Xauthority

cd /home/pi/smart-mirror && npm start

Afterwards, add this line to the bottom of ~/.config/lxsession/LXDE-pi/autostart

/home/pi/smart-start.sh &

This is better than using .bashrc because it is only executed when the lxSession starts - bashrc gets executed every time a bash session runs.
*************************************************************************************************
yeah i have mine on autoboot
theres a number of ways like
cd ~

cd smart-mirror

nano start.sh

export DISPLAY=:0

export XAUTHORITY=/home/pi/.Xauthority

cd /home/pi/smart-mirror && npm start

chmod a+rwx start.sh

and then put "/home/pi/smart-mirror/start.sh &" in the bash.rc file

**Comment by Shubham0209** [comment]
moreover this might help
https://github.com/evancohen/smart-mirror/pull/79/files#diff-04c6e90faac2675aa89e2176d2eec7d8R84

**Comment by kurtdb** [comment]
Thanks a ton for the comment. You're a lifesaver. :)

**Comment by Shubham0209** [comment]
Pleasure absloutely mine.. :smile:

**Comment by capfirepants** [comment]
HOW TO START THE SMART-MIRROR ON BOOT.
In /home/pi/, create the file called smart-start.sh with the following content:

#!/bin/bash
export DISPLAY=:0
export XAUTHORITY=/home/pi/.Xauthority
cd /home/pi/smart-mirror && npm start

Make the file owned by the user pi
chown pi:pi /home/pi/smart-start.sh
And make it executable
chmod +x /home/pi/smart-start.sh
Then, edit the file /home/pi/.config/lxsession/LXDE-pi/autostart
and add the following line to the end:

/home/pi/smart-start.sh &

Reboot the Pi and you should be good to go

**Comment by gothmate** [comment]
Thank a lot for the comments. I was lookin' up for it.

**Comment by SimonSaid00** [comment]
Hello there! First of all I would like to say  Evan that you did a great job with this project. 
Second for all- I am trying to follow Evan's start up program but it doesn't work. Does this have something to do with how my Pi is booting up ? Currently it is set to login automatically as user "Pi" and that's about it. How is yours setup in order for these  to work? Thanks a lot!

**Comment by evancohen** [comment]
@SimonSaid00 Thanks :)
Have you tried what @capfirepants has suggested above? That has worked for everyone so far.

**Comment by SimonSaid00** [comment]
Hi Evan! I did not since I wasn't sure WHERE to put the "chown pi:pi /home/pi/smart-start.sh". I am not a coder :) 

Thanks for the reply!

**Comment by SimonSaid00** [comment]
It has been done, thank you, it works :)
