### ISSUE TITLE
TV live stream

### ISSUE THREAD

**Issue by FrankMatheis** [evancohen/smart-mirror#140]
Wouldn't it be great to have the mirror play live tv streams? For example "show me news channel"
Is that possible?

**Comment by evancohen** [comment]
Well... Anything is possible, you just have to find a service that will let you do this. You can already play videos and music in the `search` branch.

**Comment by webcris77** [comment]
Hi Evan, it's prefect if you will integrate HDHomeRun
It's a network DVB-IP box that will automatically offers JSON API (HTTP) for IP streaming in local network.
Also the source code of HDHomeRun is open source.
I think that it's very simple for you to integrate this device, is just like HUE integration.
http://www.silicondust.com

**Comment by kurtdb** [comment]
While it might in theory be easy to integrate such services, without any test devices the integration will be like flying blind with 1 hand tied behind your back.

**Comment by webcris77** [comment]
Hi Kurt,   are you based in EU or US? (just to know if you need DVB-T or DVB-C/S test device )

In order to send you HDHomerun for test/dev i need to know your address for shipping.

If you have time during the wait of the demo device the syntax for channel live tv view is the following :

http://172.18.1.104:5004/auto/v1
http://172.18.1.104:5004/auto/v2
http://172.18.1.104:5004/auto/v3
http://172.18.1.104:5004/auto/v4
http://172.18.1.104:5004/auto/v5
http://172.18.1.104:5004/auto/vn…..


172.18.1.104 is my HDHomerun Internal IP Address

In any case the following is the Development Spec API provided by SiliconDusT
https://www.silicondust.com/hdhomerun/hdhomerun_development.pdf


the stream generated is h264 mp4 

Thank you


Thank you
Cris



Cristiano Fumagalli
CTO - Chief Technical Officer
 
mob.:  +39 349 1403710
cristiano.fumagalli@remago.ch
web:    www.remago.ch <http://www.remago.ch/>

**Comment by FrankMatheis** [comment]
For all Telekom IPTV customers it should be very easy. All we have to do is interating vlc.  I found a webpage (sorry, I just found a german one, but maybe someone who is able to code could understand that)  discribes the way to watch tv over vlc. Here's the link: http://www.iptv-anbieter.info/iptv-software/entertain-tv-am-pc.html
For partial translation please PN

**Comment by ojrivera381** [comment]
I love this idea. Currently i'm using Mythbuntu as a backend server with a ceton digital tuner card and a verizon fios decryption card. i then loaded Kodi on all my rpis to run live tv using mythtv plugin. Is there away to use this as a starting point. I'm no devekoper so I can only assist by being a guinea pig for ya.

**Comment by evancohen** [comment]
Agreed, it would be pretty cool to be able to watch TV. You can already watch YouTube on the `dev` branch today.

Maybe someone else can take a look at implementing this?

**Comment by ojrivera381** [comment]
Looks like this is a dead project, but could be a good resource for implementing Livetv via mythtv api.
https://github.com/MythTV-Clients/MythExpress

**Comment by evancohen** [comment]
@ojrivera381 Totally not dead... Why do you feel that way? The last big update was only 6 days ago and the latest code check-in was last night. The project is alive and well (although maybe my perspective is a bit biased).

I am a bit overwhelmed with feature requests and am still working on fixing some underlying speech issues (which I consider the highest priority because they are a part of core functionality). I'm trying to come up with a way to prioritize suggestions from the community (maybe with a GitHub thumbs up?) so that features with the highest demand get worked on.

In the interest of being totally honest, this particular request isn't very high up on my list. It would require additional hardware (speakers) and there are existing issues with audio output that would have to be fixed for this to work.

**Comment by ojrivera381** [comment]
Totally understand

**Comment by ojrivera381** [comment]
No. not your project. I meant the Mythhexpress one I linked. no update in over a year

**Comment by evancohen** [comment]
Hahaha, wow. Looks like you struck a nerve there ;) 

I wonder if we could just throw Netflix in there... that'd be interesting. They no longer have an API, but maybe we could do something tricky with windowless pop-ups or iFrames...

**Comment by ojrivera381** [comment]
I get it I would be pissed too, but you know how I fell about this project. I follow it almost everyday.

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+30

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
