### ISSUE TITLE
DS18B20 Temperature Sensing

### ISSUE THREAD

**Issue by stephwe** [evancohen/smart-mirror#166]
you get the temperature sensor with display somehow?

**Comment by evancohen** [comment]
Absolutely, you can do this with https://www.npmjs.com/package/ds18b20

**Comment by dixnor** [comment]
Hi
It has never been added to the smart-mirror this feature? Will be probably easy but my developpement skills are limited and I will be really interested to integrade some sensors in this nice project.

**Comment by justbill2020** [comment]
so this is not something that we would really integrate unless someone contributing sees the value and implements this... i would recommend checking for this in feathub and adding this to if its not already there... http://feathub.com/evancohen/smart-mirror...

the thought here is when someone comes to the project with coding skills if they see that one they can tackle it and then you get your feature in smart-mirror...

**Comment by dixnor** [comment]
I asked for this feature because I have seen it integrated in other smart mirrors projects like here https://github.com/MichMich/MagicMirror/wiki/MagicMirror%C2%B2-Modules (they have 3 or 4 sensors integrations). But I would really wanted to see such a developpement in the most interactive smart mirror I have seen. Anyway, I can try to dive in such a developpement but will take a while in my case.

**Comment by justbill2020** [comment]
we don't track these requests here... we track them on feathub...
