### ISSUE TITLE
Error when trying to install electron-prebuilt

### ISSUE THREAD

**Issue by ultrabarney** [evancohen/smart-mirror#207]
Hi all,

I have this error when installing  electron-prebuilt. Any idea how to overcome this?

(I am still a newbie. Would appreciate if anyone can help me)

Thanks
![img_20160331_152111](https://cloud.githubusercontent.com/assets/18182130/14168940/973e24de-f757-11e5-8603-018df0dcd15e.jpg)

**Comment by evancohen** [comment]
Can you include the file that the error suggested?

**Comment by ultrabarney** [comment]
I have updated to the latest smart mirror with git pull

I even try 
git clean -xdf -e config.js
npm install

It still produce the same error, the file i use is the one i downloaded on your site.

**Comment by evancohen** [comment]
Please include `npm-debug.log` otherwise it's going to be really hard to diagnose this issue. It looks to me like there is something wrong with your `package.json` - the most recent version doesn't use "wiredep", it uses "wiredep-cli" so I can tell from your screenshot that it's out of date.

Did you by any chance download the zip file from the website? That's not how you should do it, it's really only there for people who can't use git for some reason. If that's the case then you'll either have to remove it and then use `git clone` or download the new zip.

**Comment by ultrabarney** [comment]
I try to do a fresh install. And this time around i got this error (which i initially encountered yesterday) I have include both the log file and error. 

Please dl here:
http://www.filedropper.com/npm-debug
http://www.filedropper.com/error_1

**Comment by ultrabarney** [comment]
Hi there,

I managed to solve it by using another internet connection. 

Thank you!
