### ISSUE TITLE
Regexp with annyang

### ISSUE THREAD

**Issue by overflOw11** [evancohen/smart-mirror#241]
To get more flexibility in control of voice detection, we can use regexp instead of simple sentences to match command. Regexp are powerful and allow to match more sentence for one command.
I''m working on version which allow dev to set regexp in locale files. It works pretty well but I would like to have your point of view on this : 
- Is it possible to work only with regexp on the locale files
- or you prefer to keep simple sentences with the possibility to use regexp when you need it.

Thank for your comments.

**Comment by evancohen** [comment]
I'd be totally open to using Regex, the only reason I shied away from them originally was because I was already getting the flexibility I wanted with standard Annyang expressions: using `(` and `)` to make words optional, using `:` for single word in-sentence variables, `*` for wildcard, etc.

I'd be curious to know what commands you want to add/change that can't be achieved without the use of Regex. 

> Is it possible to work only with regexp on the locale files

I would be fine with this so long as we would get a significant boost in functionality/usability from switching over

> or you prefer to keep simple sentences with the possibility to use regexp when you need it.

I'm not too concerned with developer simplicity (although regex can be confusing), I'm more concerned with the end user's experience. My only hesitation is developing with regex for foreign language, I don't have enough grammatical understanding of most of the languages we now support to be able to write complex regex for them (although I guess this task could be left to other contributors). That said, it would be nice to maintain compatibility with standard Annyang syntax.

Regex is already a part of Annyang today, for instance you could:
``` javascript
var commands = {
  'hello :name': {'regexp': /^(?:hello|howdy|hi) (\w*)$/, 'callback': greetFunction}
}
```
The trick would be to support both the standard command object and the regex one (which I think wouldn't be too difficult).

**Comment by overflOw11** [comment]
I agree with your final comment, support both standard and regex command  would be better.
It''s not really difficult to add this possiblity, i just add an addRegexpCommand in the annyang service and I check in the addCommand function of the controller if the regexp is defined for the command you want to add (in the locale files).
To explain why I need regexp, this is just to get more flexibility on command calls. Maybe in English it's not the fact, but in French, you can have multiple verbs for the same action. Without regexp, it's hard to allow end users to use multiple verbs for the same command. For example, to look a video on Youtube, the end user can use the following command : Show me video of ... or Search a video of ... or just Video of... I don't want the end user have to strictly say the exact sentence of the command. I would like the command match as much as possible sentences of the end user.

**Comment by evancohen** [comment]
Can't this be accomplished with: `"(show)(search)(me)(a) video of*"`? Maybe in French it's more complex than this, but it seems relatively straightforward. Sure, syntactically it's not quite as nice as `"(show|search) (me|a) video of *"`, but they are effectively the same.

**Comment by overflOw11** [comment]
You're right ! For the end user, this is the same as the regexp. This is even better for the end user because he can say whatever he want before "video of...", contrairly to the regexp. I keep my regexp branch internal. If you need it, ask to me. I close this suggestion/question.

Thank for your comments.
