### ISSUE TITLE
Displayed time is not correct

### ISSUE THREAD

**Issue by rsandstroem** [evancohen/smart-mirror#25]
The time shown on the main page is always a couple of minutes behind the actual time for me. Using the voice command to get the time gives the correct time in the debug window however, so it looks as it is not updating correctly.

**Comment by evancohen** [comment]
This is probably due to the fact that the clock updates every 60 seconds, assuming that you launched it at the top of the minute, and not updating the time every second. What surprises me is that the clock could ever be more than 60 seconds behind.

I've update the controller to update the clock every second (hopefully this isn't too much of a performance hit).
