### ISSUE TITLE
Any interest in www.todoist.com service?

### ISSUE THREAD

**Issue by yaydogan** [evancohen/smart-mirror#292]
I have a working service for www.todoist.com. If there is enough interest and people think it is not redundant to the existing reminder service, I can create a PR for this function. 

@evancohen  what is your take?

**Comment by evancohen** [comment]
Absolutely :D syncing reminders to a service (and not just having them stored locally) would be rad!

**Comment by kurtdb** [comment]
I'm also a huge fan to make this a hosted feat in stead of using the browser storage. (which could be a bit volatile due to some code changes)

**Comment by yaydogan** [comment]
Thanks for your feedback guys. I realized code layout changed a bit since I developed todoist service in my repository. I am working on porting my code to a new branch now. I will raise a PR soon.

**Comment by GobleSt** [comment]
I haven't used the reminders yet and did not realize they would be local.  I was thinking they would integrate with my iCAL feed.  Is there not a way to use existing google calendar?

**Comment by evancohen** [comment]
@GobleSt the iCals that we use are read-only. You're right though, that would be awesome to integrate. The barrier to entry here is that those APIs require O-Auth - which would mean that you would have to type in your Username and password on the mirror every once and a while (which would be lame)

I have some ideas about how to address this long term, including a companion app or locally hosted webserver #48, but due to the complexity I'm waiting until all the keyword spotting stuff is working and the mirror is in a stable state before I go and try to do this.

**Comment by kurtdb** [comment]
@yaydogan any update on this one ?

**Comment by yaydogan** [comment]
@kurtdb  I have it working based on old version of code so I have to make changes to fit into new code layout. Started on it on a new branch, hoping to get the PR out next week.

**Comment by evancohen** [comment]
@yaydogan any chance you are still working on this?

**Comment by justbill2020** [comment]
@yaydogan haven't seen any updates regarding this since Sep 22... is this still being worked on?

**Comment by justbill2020** [comment]
Migrated to http://feathub.com/evancohen/smart-mirror/+15

Issue will be closed and tracked on feathub moving forward. Please refer to feathub for all future comments on this suggestion.
