### ISSUE TITLE
Trouble changing time and date to european formats

### ISSUE THREAD

**Issue by SenadM** [evancohen/smart-mirror#376]
Tried to change the language in the config file to en-GB. Hasn't worked. This includes the date and time of the mirror (24h and DD/MM/YYYY)

**Comment by evancohen** [comment]
Looks like there is a bug in the controller when registering locals for `moment`:
https://github.com/evancohen/smart-mirror/blob/dev/js/controller.js#L44

This is an issue with moment as they don't support an alias between the fully qualified locale and the locale that they provide, ie: French is `fr` while UK English is `en-gb`. That makes things complicated for us, because we always need the fully qualified locale for speech recognition. 

There's proudly a simple work-around here, I'll take a look tonight.

**Comment by SenadM** [comment]
Great Evan, thanks. I made it work with some workarounds, so now, I have the Danish date and time format. Had trouble with the weather and traffic info because I changed the language to "da", but ended up fixing it for now.

**Comment by evancohen** [comment]
Yeah, it's complicated because each service that needs the language wants it in a slightly different format.

**Comment by evancohen** [comment]
I now have a solution to this issue (after totally dropping the ball on it) 🏀. We'll need to create fully qualified alias for each of the moment locales by extending the existing ones: http://momentjs.com/docs/#/customization/

Shouldn't be difficult at all!

**Comment by evancohen** [comment]
Fixed in dev :)
