### ISSUE TITLE
Suggestion:Why not JasPer.

### ISSUE THREAD

**Issue by taran27** [evancohen/smart-mirror#430]
**_well google API's are great but not efficient for daily use why not we use jasper a open source project which is offline and good for speech plus contains self developing functions._**

**Comment by evancohen** [comment]
Hey @taran27, thanks for the suggestion!

Jasper typically relies on Pocketsphinx, is written in Python, and is likely too bloated for the smart-mirror.
Pocketsphinx is great, but the accuracy leaves a lot to be desired and it's also significantly slower on a low powered device like the Pi.

I'd rather not go back to a world where the project is half Python, there are enough moving parts already. On top of that we'd likely need a (very?) complex IPC to get the self developing functions to work with the mirror. As an aside, Jasper actually also uses Google Speech: https://jasperproject.github.io/documentation/configuration/#stt

The [Sonus](https://github.com/evancohen/sonus) library, while immature in comparison, is much better suited for the smart mirror because:
- Super performant hotword detection
- Google Cloud Speech (not to be confused with the older Google Speech that Jasper uses)
- Uber small footprint (especially at idol)

Someday I'll revisit Pocketsphinx support for Sonus, but until that time a could speech recognizer is the way to go.

**Comment by taran27** [comment]
yo thanks @evancohen thats gr8 den..
