### ISSUE TITLE
jack server is not running or cannot be startd

### ISSUE THREAD

**Issue by kermit-kr** [evancohen/smart-mirror#441]
pi@raspberrypi:~/smart-mirror-master $ npm start dev

> smart-mirror@0.0.4 start /home/pi/smart-mirror-master
> electron main.js  "dev"

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

Annyang does not work, and the above message appears.

There is no error in the source code.

I get the same error if I kill and run pulseaudio again

I do not know what to do.

**Comment by evancohen** [comment]
Please ensure that you are running the latest version of Raspbian and the mirror. There are audio issues with older versions of both.

**Comment by justbill2020** [comment]
@evancohen a few tthoughts... can we (read: you, lol) "version" the smart-mirror... so that when we npm smartmirror version it spits out a version number? so we can verify what version people are on... obviously if the command doesn't work its not current...

also we need to go through and edit the old audio issues where we were debugging pulse audio so that its not misleading people down a rabbit hole...

**Comment by evancohen** [comment]
Agreed with those thoughts!

**Comment by justbill2020** [comment]
@kermit-kr is this now resolved? 

If not please update us and let us know how we can help. If it is please comment what solved the issue and then close the issue. thank you. 

[Also, we're available on gitter to help assist you in real time.](https://gitter.im/evancohen/smart-mirror)

**Comment by kermit-kr** [comment]
The problem is well solved.
Thank you.

**Comment by justbill2020** [comment]
@kermit-kr can you please post here how you solved the issue?

**Comment by kermit-kr** [comment]
The problem was caused by the low node.js version.

The node.js version has been raised and fixed.

Thank you!
