### ISSUE TITLE
any possibility, to prevent it from listening a few hours?

### ISSUE THREAD

**Issue by abendplays** [evancohen/smart-mirror#496]
Hi guys, 
my problem is that the mirror triggers my voice sometimes, even if the sensitivity is pretty good.. 
Is there any possibility of implementing a "timeout", which prevents the mirror from sending google hours of voice without getting anything usefull back?

**Comment by evancohen** [comment]
I think this is actually a UI bug (see #477). The mirror will typically only send a single utterance to Google - but for some reason there's a glitch right now that's causing the bottom glow of the mirror to persist even after it is done "listening".

I'm going to close this out because I think it's a duplicate, but feel free to let me know if you think otherwise.
