### ISSUE TITLE
Command error

### ISSUE THREAD

**Issue by lemonalemon** [evancohen/smart-mirror#525]
I've finished setting up.
And micro-recognition is possible.
But after saying "What can i say", other commands do not work.
And say "smart mirror", the white bar on the bottom comes up, and so my voice is recognized.
Is this originally uncomfortable? Can not I just recognize the command I want?

And I entered the calendar and rss in "config.json", but I can not see it in the mirror screen.
Please help the novice developer.

**Comment by justbill2020** [comment]
@lemonalemon 
7 out of 10 times this is due to billing not being enabled in Google Cloud Platform. 
2 out of 10 times the billing is enabled and the project isn't attached to the billing account. 
1 out of 10 times the billing is enabled and the project is attached but the billing account was closed for some reason and needs to be reopened.

I hope this helps.

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by evancohen** [comment]
This might actually be a bug, but if it is it's already fixed in the dev branch. Can you try that?

**Comment by lemonalemon** [comment]
The payment would have been complete. I also received a payment letter. And it was all usable. And I do not know how to use the dev branch. Could it be a bug? Please confirm. I am still suffering.

Oh, and is there any way I have to shout "smart mirror"? It is too uncomfortable.

**Comment by taran27** [comment]
hmmm.. which microphone r u using plus did u trained your model @snowboy.kitt..???

**Comment by lemonalemon** [comment]
@taran27 I used a usb mic available in raspberry pi.

**Comment by evancohen** [comment]
You might want to bump up the input volume on your mic if it's not picking you up at a distance.

To use the latest dev branch (from the smart mirror folder):
```
git checkout dev
git pull
```

**Comment by lemonalemon** [comment]
@evancohen 
I entered that command. What should I do?

git checkout dev
```
error: Your local changes to the following files would be overwritten by checkout:
	index.html
Please, commit your changes or stash them before you can switch branches.
Aborting
```
git pull
When you use the command, it is called the latest version.

**Comment by evancohen** [comment]
You've modified `index.html`. You can either commit your changes `git commit -am "some message"`, stash them `git stash`, or throw them away `git checkout index.html`.

Then try those commands again.

I'm going to merge this issue with #526 because it's tracking the same problem. I'm going to try to push out an update tonight.
