### ISSUE TITLE
Capture movement from camera

### ISSUE THREAD

**Issue by evancohen** [evancohen/smart-mirror#536]
As an alternative motion input source, we should track camera movement (so people don't need additional hardware on top of what they've already got)

### Expected Behavior
 

As a part of the config, you should be able to specify if you are using a timer, IR motion sensors, or camera.
No idea what the performance implications would be for monitoring your webcam like this.

### Current Behavior

We're currently limited to a timer and motion sensor (that requires additional libraries). It'd be nice to explore options to give us the same functionality but don't require that additional hardware.

### Context

I've seen some other people do interesting things like this (looking at you @rabidaudio)

**Comment by justbill2020** [comment]
booo.... privacy concerns.... boooo..... bathroom creeper alert.... lol

**Comment by rabidaudio** [comment]
I've got a little proof-of-concept going on [my fork](https://github.com/rabidaudio/smart-mirror/tree/webcam). It's currently just a short python script that emulates `motion.js`'s console messages. It should be pretty trivial to convert it to javascript, but at the time I wasn't aware there were OpenCV bindings for javascript. 

I'm using a webcam because I have a spare and also because it has a microphone, but I imagine most people would want to use the Raspberry Pi camera module. I suspect OpenCV will treat these the same, but I haven't played with the Pi's camera module before. 

Running the script chews up a bunch of CPU cycles, but it does run, at least on a Pi 3 model B. Currently I'm opening a video stream and processing every frame, but it should be possible to take a picture periodically (e.g. every second) and then sleep. I'll play with this tonight and see how it goes.

**Comment by justbill2020** [comment]
you'll probably need to rebase your branch from the upstream dev... but if you can port the python to js and incorporate it into motion.js I can set up a drop down box in the configUI to use either pir or webcam

**Comment by evancohen** [comment]
[This example](https://benjaminhorn.io/code/motion-detection-with-javascript-and-a-web-camera/) scales down the image to reduce comparison times (and as you mentioned, we wouldn't necessarily have to compare every frame. You could do < 10 FPS and it'd still be effective.

I doubt we'd need the full power of OpenCV to get this to work. That said, if it's performant enough we could do some pretty cool things with it :)

**Comment by sdetweil** [comment]
I just submitted a pull request that supports this, uses https://motion-project.github.io/ for the detection, 
and a small enhancement to the autosleep plugin.

**Comment by sdetweil** [comment]
add 0.26
