### ISSUE TITLE
[Q] how can i load image(file) on the screen with voice command

### ISSUE THREAD

**Issue by nevido** [evancohen/smart-mirror#628]
i want to load image file on the screen with voice command
so i'm trying to modify some files by AngularJS
but failed..
how can i do it.. T T

/home/pi/smart-mirror/smart.jpg

![image](https://cloud.githubusercontent.com/assets/25813260/24508370/28ad0132-159e-11e7-8b75-3a8b64e8a12d.png)

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Environment name and version (e.g. Raspberry Pi 3, node.js 5.4):
* Operating System and version (e.g. Raspbian, Ubuntu, OSX):

**Comment by nevido** [comment]
I mean  
Wanna load image on the screen after success of voice command

**Comment by justbill2020** [comment]
a specific voice command or all voice commands?

**Comment by justbill2020** [comment]
please look at the development and contribution guide 
https://docs.smart-mirror.io/docs/development_and_contributing.html

probably not best to dev on the pi directly... 

you can also look at how the giphy plugin works and instead of the api request load the image as the "response" and then duplicate the giphy related statements in the index.html file also you'll need to create a view... 

Also, we're available on [discord chat](https://discord.gg/EMb4ynW) to help assist you in real time.

**Comment by nevido** [comment]
@justbill2020 Thank you for the tip  i will read it.. and try
really thank you
