### ISSUE TITLE
Static noise from speaker

### ISSUE THREAD

**Issue by poetic420** [evancohen/smart-mirror#661]
Running ras pi 3
when opening smart mirror there is a static noise coming from the speaker ..
this is very annoying, any advice?

**Comment by evancohen** [comment]
Could be caused by an out-of-date driver/configuration. Try this: https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=136445

It could also be an issue with isolation on the board (leaking electricity when it's working hard) which you could probably fix with https://www.ebay.com/i/111723982193?chn=ps&dispItem=1

Give that first one a shot before you start throwing money at the problem though :)

**Comment by poetic420** [comment]
thanks for replay!
when i add the following (audio_pwm_mode=2) line In /boot/config.txt
the static noise stops!
but when i play you tube video it gets super laggi, i mean sound and video gets messed up and very slow.. 
why is that? its better withe static noise at last it works hhh

Thanks for the help!!

**Comment by poetic420** [comment]
I also have that sound car you advised me..
How do i configure the ras pi to output sound through the card?
I also have 3.5 mm jack mic, can i use it also?
Thanks for the help!!

**Comment by evancohen** [comment]
You should be able to configure your output device by following the instructions for [Manual Audio Input and Output configuration](https://docs.smart-mirror.io/docs/configuring-sound.html#manual-audio-input-and-output-configuration).

Not sure why changing the pwm mode would cause lag like that, I'm no linux audio expert... Maybe some googling will give you the answer.

**Comment by poetic420** [comment]
Problem kind of fixed hhh...
I turned up the pi`s volume to max:
from pi desktop, press raspberry icon  
-audio device setting
-select controls
-select icon "pcm"
-turn vol up

Thank you for the help Evan!!!
