### ISSUE TITLE
Configurable Mirror Localization

### ISSUE THREAD

**Issue by danielccm** [evancohen/smart-mirror#71]
Have the mirror somehow either ask in what language you'd like it to be or just figure it out automatically via the coordinates.

**Comment by kurtdb** [comment]
I think this might be harder to implement as you would expect.

For example: say your mirror is in Brussels. There are a lot of different nationalities living there, next to the fact that in Brussels there are both Dutch speaking and French speaking people. (and not all of them are bilingual) So how would we determine which language the person will speak?

**Comment by flyingzombies** [comment]
Well..just ask them like the big os's do.
Maybe someone wants an english mirror although he lives in germany or france.

**Comment by kurtdb** [comment]
What you are suggesting is that we create a separate file containing the translations for all the commands? Feel free to take a crack at it.

What I've been looking into is translation for the dates and days of the week through angular and momentjs. It could be an added bonus if the other stuff was also translated.

**Comment by flyingzombies** [comment]
i guess in this early sate of development it would be enough to offer the key things like date, time or weather in different languages.

the language could be set via a config file while you set up the mirror.

specific commands could either be translated by experienced users themselves, also written in a kind of config file or added later.
at the moment I guess it's enough to let them in english, since most of the development is done in and from english speaking people.

**Comment by ctutu** [comment]
I think a good way will to set language in config file and translation in specific langue file with commande, day like kurtdb said.. The standard must be in English and for other language maybe some contributor could translate in own mother tongue.

Whats do you think ?

**Comment by danielccm** [comment]
I volunteer to do it in Spanish! what files do I have to modify?

**Comment by kurtdb** [comment]
None right now as no system is set up yet.

**Comment by danielccm** [comment]
Ok! I'll keep watching this space then...

**Comment by evancohen** [comment]
This already exists as a config value, it's just not used anywhere. I'll find some time this week to add localized weather and take a look at what implementing dates would look like.

**Comment by flyingzombies** [comment]
i could translate to german

2016-02-22 20:12 GMT+01:00 Evan Cohen <notifications@github.com>:

**Comment by gothmate** [comment]
I am translating to portuguese, with annyang commands also.
But I'm having some difficulty to turn the forecast messages to "pt". I've read all documentation and still don't know how.

**Comment by ctutu** [comment]
hello, to translate in french weather description and day forcast I add this two things in the index.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.5.0/angular-locale_fr-ch.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/locale/fr.js"></script>
You just need to modifie both file with you language

**Comment by gothmate** [comment]
@ctutu what two things?

**Comment by teemuha** [comment]
@evancohen Could moment.js  be used to provide localized dates and times? It already includes multiple locales http://momentjs.com/

**Comment by evancohen** [comment]
@teemuha yeah, it could. The problem is that it's more than just dates that need localization. I've got a couple of different options prototyped, but none of them are as clean as I'd like so I'm holding off until I can get it right. I don't want to push something in that is half broken and then make people do a bunch of work to upgrade when I fix it.
