### ISSUE TITLE
Question: What was the reason to use electron?

### ISSUE THREAD

**Issue by timaschew** [evancohen/smart-mirror#750]
Probably very naive question:

I just wonder why not just running a webapp on Chrome/Chromium?

**Comment by radiogrammer** [comment]
i doubt there is a such thing as a naive question any more than there is a dumb one...

**Comment by justbill2020** [comment]
It was a simple framework to run it as a desktop app.

**Comment by timaschew** [comment]
So the reason was to provide an executable to avoid users to install Node.js?

**Comment by evancohen** [comment]
I wrote a really detailed post about this decision on an issue somewhere this repo but can't find it, but long story short:  

We use Electron because we "broke" `webkitSpeechRecognition()` in Chromium (yes, the mirror originaly ran in Chromium). We had loads of mirrors constantly streaming all of their audio to Google's servers. In the early days of the mirror it constantly streamed your audio to a recognition server (no keyword spotting). I can only assume Google didn't like that, we were using their resources for free, so they shut down the functionality for Chromium (still works in Chrome to date). The work-around for this was to use Electron with custom developer keys, which would give you 50 requests/day. Obviously you'd burn through these in a very short period of time, because the mirror was always streaming audio. After a substantial amount of head banging I created Sonus.

During the head-banging era, the smart mirror used to use a Python sub-process for keyword spotting, and then used `webkitSpeechRecognition()` within Electron for streaming recognition. This was done for increased privacy and to reduce the number of requests made so the mirror could funciton all day (instead of just for the first half or so). But that wasn't great either because you were still limeted to 50 requests/day. I managed to get into the Google Cloud Speech Pilot program and prototyped Sonus to deal with keyword spotting and streaming recognition (to make my life easier, but also because I figured other people would find it useful).

There are, of course, some complications with Electron...

- Getting native binaries to rebuild and packaged for Electron is tricky, as some have discovered: evancohen/sonus#86
  - Side note, I did make [sonus-electron-boilerplate](https://github.com/evancohen/sonus-electron-boilerplate), but I'm not sure if that directly addresses the problem.
- I set up a build process for the great folks over at Kitt.ai so we can have pre-built binaries for Snowboy (instead of having to build them locally), but unfortunetly this doesn't produce binaries for Electron.

For this reason, the smart mirror uses an IPC for Sonus (so it's is running on your local version of node, instead of with the version that's bundled with electron - it's a totally separate process).

As for your point about having an executable, that's a huge plus for Electron, but isn't something that's been implemented yet. I looked into it a while ago and concluded that it would require some centralized updating server and I think that's too much to maintain.

Anyway, that's probably more information than you were looking for, but now anyone else who is curious about how this all came to be can read this :smile:

**Comment by justbill2020** [comment]
No, you still require custom developer keys. As @evancohen stated in his last comment

> As for your point about having an executable, that's a huge plus for Electron, but isn't something that's been implemented yet. I looked into it a while ago and concluded that it would require some centralized updating server and I think that's too much to maintain.

An executable would require us to configure a config utility and maintain that code space. I started on a project similiar to this several months ago and decided that it would be contrary to the level of time and attention the main contributors could provide at this time.

**Comment by timaschew** [comment]
Maybe I was wrong about the fact that these keys are needed for electron anyway?

Of course you need anyway keys for speech recognition API which each user needs to create. But those keys are not related to electron, right? You can use them in Node.js directly or even in the browser maybe.

**Comment by evancohen** [comment]
@timaschew I'm still into Electron at the high level. It makes running, development, etc. a whole lot easier. Going to close out this issue, but feel free to ask more questions :)
