### ISSUE TITLE
Logitech Harmony Integration?

### ISSUE THREAD

**Issue by CsStorms** [evancohen/smart-mirror#77]
I'm new to all this.  Wondering if it's possible to integrate with the Logitech Harmony system like it does with the Hue.

For instance.  I have a activity that is "Watch Cable" which I can select on my phone or on the Harmony remote.  Would it be possible to integrate that into the mirror where I can say "Watch Cable" and it turns on whatever the Harmony has set for that activity?  I have no idea how to make that happen so it's more of a question or suggestion to look into than anything.

Great work on all this, it's fantastic!

**Comment by evancohen** [comment]
Absolutely possible, but I don't have access to their API. I [requested access](https://www.myharmony.com/en-us/harmony-api) a little over 4 months ago and still haven't gotten it. I've done some experimental integration with the IFTTT maker channel and it looks like there is a [harmony channel](https://ifttt.com/harmony), so that's probably your best bet.

You'll want to write an ifttt service (see the js/*-service.js files for some examples integrating with HTTP APIs). Just make sure that after you create it you inject it into js/controller.js and register a new voice command so you can actually trigger the call.

I'm going to close this issue, but feel free to drop into the [gitter chant](https://gitter.im/evancohen/smart-mirror) if you have any more questions.
